WebAutomationSystem/Areas/AdminArea/Controllers/SystemPartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAutomationSystem.DataModelLayer.Entities;
using WebAutomationSystem.DataModelLayer.Services;
using WebAutomationSystem.DataModelLayer.ViewModels;

namespace WebAutomationSystem.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "AdminAreaPanel")]
    public class SystemPartController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        private readonly RoleManager<ApplicationRoles> _roleManaegr;

        public SystemPartController(IUnitOfWork context, IMapper mapper, RoleManager<ApplicationRoles> roleManaegr)
        {
            _context = context;
            _mapper = mapper;
            _roleManaegr = roleManaegr;
        }

        public IActionResult Index()
        {
            FillTreeView();
            return View();
        }

        private void FillTreeView()
        {
            List<TreeViewModel> node = new List<TreeViewModel>();

            node.Add(new TreeViewModel
            {
                id = "1",
                text = "اجزای سیستم",
                parent = "#"
            });

            foreach (ApplicationRoles role in _context.roleManagerUW.Get(r => r.RoleLevel != "0"))
            {
                node.Add(new TreeViewModel
                {
                    id = role.Id.ToString(),
                    parent = role.RoleLevel.ToString(),
                    text = role.Description
                });
            }

            ViewBag.SystemPart = JsonConvert.SerializeObject(node);
        }

        [HttpGet]
        public IActionResult AddSystemPart(string id, string parentname)
        {
            ViewBag.parentname = parentname;
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSystemPart(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mapModel = _mapper.Map<ApplicationRoles>(model);
                IdentityResult roleResult = await _roleManaegr.CreateAsync(mapModel);
                if (roleResult.Succeeded)
                {
                    FillTreeView();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
    }
}

WebAutomationSystem/Areas/AdminArea/Views/SystemPart/AddSystemPart.cshtml
@model WebAutomationSystem.DataModelLayer.ViewModels.RoleViewModel
@{
    ViewData["Title"] = "افزودن اجزای جدید";
}


<div class="content">

    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 #cbcbcb; border-radius:px;">
        <span style="font-weight:bold;">
            <i class="icon-accessibility"></i>
            فرم تعریف جز جدید زیرمجموعه <span style="color:darkgreen;">@ViewBag.parentname</span>
        </span>
    </div>


    <div class="panel panel-body container-fluid" style="border-radius:px; box-shadow:3px 1px 1px 0 #cbcbcb;
                background-color:#ebebeb;">

        <form asp-controller="SystemPart" asp-action="AddSystemPart" method="post">
            <div class="col-md-8 col-md-offset-2">
                <!--Description-->
                <div>
                    <label asp-for="Description" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Description" type="text" class="form-control custominput" placeholder="نام فارسی دسترسی ..." autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <input asp-for="RoleLevel" value="@ViewBag.id" class="hidden" />

                <!--Name-->
                <div>
                    <label asp-for="Name" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Name" type="text" class="form-control custominput" placeholder="نام انگلیسی دسترسی ..." autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <input type="submit" 
                           value="ثبت بخش جدید" class="btn btn-outline-primary pull-right" />
                </div>
            </div>
        </form>
    </div>

</div>

WebAutomationSystem/Areas/AdminArea/Views/SystemPart/Index.cshtml
@{
    ViewData["Title"] = "چارت اجزای سیستم";
}

<div class="content">

    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 #cbcbcb; border-radius:px;">
        <span style="font-weight:bold;">
            <i class="icon-accessibility"></i>
            اجزای سیستم
        </span>
    </div>

    <div style="margin-bottom:5px;">
        <a class="btn btn-outline-primary" href="#" id="navigationtoadd" title="ثبت بخش جدید">
            <i class="glyphicon glyphicon-plus"></i>
            ثبت بخش جدید
        </a>
    </div>

    <div class="alert" style="border:1px solid #cbcbcb; font-weight:bold; margin-top:15px;
                                text-align:center; font-size:15px; background-color:#D9F8C4;box-shadow: 3px 1px 1px 0 grey;border-radius:5px;">
        جهت افزودن بخش جدید ابتدا یک جز را از درخت اجزا انتخاب نمایید.
    </div>

    <div class="panel panel-body container-fluid overflow-auto" style="border-radius:px; height:450px;
                    box-shadow:3px 1px 1px 0 #cbcbcb; background-color:#ebebeb;">
        <div id="jstreesyspart">
        </div>
    </div>

</div>


@section AdminScripts{
    <script>
        $(function () {
            $("#jstreesyspart").on("changed.jstree", function (e, data) {

                var i, j;
                var postedItems = [];

                j = data.selected.length;
                for (var i = 0; i < j; i++) {
                    postedItems.push({
                        text: data.instance.get_node(data.selected[i]).text,
                        id: data.selected[i],
                        parent: data.node.parents[0]
                    });
                }
                if (data.selected.length) {
                    $('#navigationtoadd').click(function () {
                        if (this.id == 'navigationtoadd') {
                            ///Add
                            var id = postedItems[0].id;
                            var parentname = postedItems[0].text;
                            $('#navigationtoadd').attr("href", "/AdminArea/SystemPart/AddSystemPart?id=" + id +
                                "&parentname=" + parentname);
                        }

                    });
                }

            }).jstree({
                "core": {
                    "themes": {
                        "variant": "large"
                    },
                    "data": @Html.Raw(ViewBag.SystemPart) ,
                },
                "checkbox": {
                    "Keep_selected_style": false
                },
            }).on("loaded.jstree", function () {
                $.jstree.reference('#jstreesyspart').open_all();
            });
        });
    </script>
}