WebAutomationSystem/Areas/UserArea/Controllers/LetterListController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using Stimulsoft.Base;
using Stimulsoft.Report;
using Stimulsoft.Report.Components;
using Stimulsoft.Report.Mvc;
using WebAutomationSystem.CommonLayer.PublicClass;
using WebAutomationSystem.DataModelLayer.Entities;
using WebAutomationSystem.DataModelLayer.Repository;
using WebAutomationSystem.DataModelLayer.Services;
using WebAutomationSystem.DataModelLayer.ViewModels;

namespace WebAutomationSystem.Areas.UserArea.Controllers
{
    [Area("UserArea")]
    [Authorize(Roles = "UserAreaPanel")]
    public class LetterListController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly ILettersRepository _iletter;
        private readonly IWebHostEnvironment _hosting;

        public LetterListController(IUnitOfWork context, UserManager<ApplicationUsers> userManager, ILettersRepository iletter, IWebHostEnvironment hosting)
        {
            _context = context;
            _userManager = userManager;
            _iletter = iletter;
            _hosting = hosting;

            var stimulKey = Path.Combine(_hosting.ContentRootPath, "wwwroot\\reports\\license", "license.key");
            if (System.IO.File.Exists(stimulKey))
            {
                StiLicense.LoadFromFile(stimulKey);
            }
        }

        [Authorize(Roles = "RecievedLetter")]
        public IActionResult Index(byte classificationradio = 0, byte replyradio = 2, byte attachmentradio = 2, byte readradio = 2, byte searchTypeselected = 0, byte immediatelytype = 0, string inputsearch = "", string fromdate = "", string todate = "")
        {
            //طبقه بندی
            switch (classificationradio)
            {
                case 0:
                    ViewBag.classificationradio_all = "checked";
                    break;
                case 1:
                    ViewBag.classificationradio_1 = "checked";
                    break;
                case 2:
                    ViewBag.classificationradio_2 = "checked";
                    break;
                case 3:
                    ViewBag.classificationradio_3 = "checked";
                    break;
            }
            //درخواست پاسخ
            switch (replyradio)
            {
                case 0:
                    ViewBag.radioreply_0 = "checked";
                    break;
                case 1:
                    ViewBag.radioreply_1 = "checked";
                    break;
                case 2:
                    ViewBag.radioreply_all = "checked";
                    break;
            }
            //پیوست
            switch (attachmentradio)
            {
                case 0:
                    ViewBag.attachmentradio_0 = "checked";
                    break;
                case 1:
                    ViewBag.attachmentradio_1 = "checked";
                    break;
                case 2:
                    ViewBag.attachmentradio_all = "checked";
                    break;
            }
            //وضعیت خوانده شدن
            switch (readradio)
            {
                case 0:
                    ViewBag.radioread_0 = "checked";
                    break;
                case 1:
                    ViewBag.radioread_1 = "checked";
                    break;
                case 2:
                    ViewBag.radioread_all = "checked";
                    break;
            }

            ViewBag.searchTypeselected = searchTypeselected;
            ViewBag.immediatelytype = immediatelytype;
            ViewBag.inputsearch = inputsearch;
            ViewBag.fromdate = fromdate;
            ViewBag.todate = todate;

            if (fromdate == "" || fromdate == null)
            {
                fromdate = "1300/01/01";
            }
            if (todate == "" || todate == null)
            {
                todate = "1600/01/01";
            }

            var model = _iletter.
                MyLetter(_userManager.GetUserId(HttpContext.User),
                         ConvertDateTime.ConvertShamsiToMiladi(fromdate),
                         ConvertDateTime.ConvertShamsiToMiladi(todate),
                         classificationradio, replyradio, attachmentradio, readradio, searchTypeselected, immediatelytype, inputsearch);
            return View(model.OrderByDescending(l => l.LetterID));
        }


        [Authorize(Roles = "RecievedLetter")]
        public IActionResult IndexSecretariat(byte classificationradio = 0, byte replyradio = 2, byte attachmentradio = 2, byte readradio = 2, byte searchTypeselected = 0, byte immediatelytype = 0, string inputsearch = "", string fromdate = "", string todate = "")
        {
            //طبقه بندی
            switch (classificationradio)
            {
                case 0:
                    ViewBag.classificationradio_all = "checked";
                    break;
                case 1:
                    ViewBag.classificationradio_1 = "checked";
                    break;
                case 2:
                    ViewBag.classificationradio_2 = "checked";
                    break;
                case 3:
                    ViewBag.classificationradio_3 = "checked";
                    break;
            }
            //درخواست پاسخ
            switch (replyradio)
            {
                case 0:
                    ViewBag.radioreply_0 = "checked";
                    break;
                case 1:
                    ViewBag.radioreply_1 = "checked";
                    break;
                case 2:
                    ViewBag.radioreply_all = "checked";
                    break;
            }
            //پیوست
            switch (attachmentradio)
            {
                case 0:
                    ViewBag.attachmentradio_0 = "checked";
                    break;
                case 1:
                    ViewBag.attachmentradio_1 = "checked";
                    break;
                case 2:
                    ViewBag.attachmentradio_all = "checked";
                    break;
            }
            //وضعیت خوانده شدن
            switch (readradio)
            {
                case 0:
                    ViewBag.radioread_0 = "checked";
                    break;
                case 1:
                    ViewBag.radioread_1 = "checked";
                    break;
                case 2:
                    ViewBag.radioread_all = "checked";
                    break;
            }

            ViewBag.searchTypeselected = searchTypeselected;
            ViewBag.immediatelytype = immediatelytype;
            ViewBag.inputsearch = inputsearch;
            ViewBag.fromdate = fromdate;
            ViewBag.todate = todate;

            if (fromdate == "" || fromdate == null)
            {
                fromdate = "1300/01/01";
            }
            if (todate == "" || todate == null)
            {
                todate = "1600/01/01";
            }

            var model = _iletter.
                MyLetter(_userManager.GetUserId(HttpContext.User),
                         ConvertDateTime.ConvertShamsiToMiladi(fromdate),
                         ConvertDateTime.ConvertShamsiToMiladi(todate),
                         classificationradio, replyradio, attachmentradio, readradio, searchTypeselected, immediatelytype, inputsearch);
            return View(model.OrderByDescending(l => l.LetterID));
        }

        [HttpGet]
        public IActionResult ReferLetter(int LetterID, string mainUserId)
        {
            if (LetterID == 0)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            ViewBag.JobIdList = JsonConvert.SerializeObject(_context.jobsChartUW.Get().Select(j => j.JobsChartID).ToList());
            TreeViewCreator();

            ViewBag.userJobId = _context.userJobUW.Get
                (u => u.UserID == _userManager.GetUserId(HttpContext.User) && u.IsHaveJob == true).Select(s => s.JobID).Single();
            ViewBag.LetterId = LetterID;
            ViewBag.MainUserId = mainUserId;
            return PartialView("_ReferLetter");
        }

        [HttpPost]
        public IActionResult ReferralLetter
            (int LetterID, string SelectedUserToRefer, string MainUserId, string Description)
        {
            try
            {
                List<TreeViewModel> items = JsonConvert.DeserializeObject<List<TreeViewModel>>(SelectedUserToRefer);
                if (items.Count == 0)
                {
                    return Json(new { status = "nouserselected" });
                }
                for (int i = 0; i < items.Count; i++)
                {
                    string RecievedUserID = _iletter.GetUserIdFromJobID(Convert.ToInt32(items[i].id));
                    //کنترل عدم ارجاع تکراری

                    var checkBeforeRefer = _context.referralLettersUW.Get
                        (Rl => Rl.LetterID == LetterID &&
                        Rl.RecieveReferUserID == RecievedUserID &&
                        Rl.mainUserID == MainUserId);

                    if (checkBeforeRefer.Count() == 0)
                    {
                        ReferralLetters RL = new ReferralLetters
                        {
                            LetterID = LetterID,
                            ReadType = false,
                            mainUserID = MainUserId,
                            ReferUserID = _userManager.GetUserId(HttpContext.User),
                            RecieveReferUserID = RecievedUserID,
                            ReferDate = DateTime.Now,
                            Description = Description
                        };

WebAutomationSystem/Areas/UserArea/Views/LetterList/_ReferLetter.cshtml
@{
    Layout = null;
}

<style>
    .selected {
        background-color: #cbcbcb;
        color: white;
    }

    .swal2-modal{
        width:280px !important;
    }
</style>

<div class="modal-header" style="background-color:#cbcbcb; color:white; border-radius:5px 5px 0 0;">
    <button type="button" class="close pull-left" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">ارجاع نامه</h4>
</div>

<div class="content">

    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 #cbcbcb; border-radius:px;">
        <span style="font-weight:bold;">
            <i class="icon-notebook"></i>
            انتخاب کارکنان مجاز جهت ارجاع نامه
        </span>
    </div>

    <div class="panel panel-body container-fluid"
         style="border-radius:px; height:250px; overflow:auto; box-shadow:3px 1px 1px 0 #cbcbcb; background-color:#ebebeb;">

        <div class="col-md-12 col-xs-12" style="margin-top:20px;">
            <div id="jstreejobs"></div>
        </div>
    </div>

    <div class="col-md-12 col-xs-12">
        <div class="col-md-8 col-md-offset-2 col-xs-12">
            <label class="col-md-3 col-xs-12">پانوشت :</label>
            <textarea id="txtdescription" class="col-md-9 col-xs-12 custominput"
                      style="height:70px;" placeholder="پانوشت نامه ..."></textarea>
        </div>
    </div>
</div>

<input id="LetterId" name="LetterId" type="text" class="hidden" value="@ViewBag.LetterId" />
<input id="SelectedUserToRefer" name="SelectedUserToRefer" type="text" class="hidden" />
<input id="MainUserId" name="MainUserId" type="text" class="hidden" value="@ViewBag.MainUserId"/>



<div class="modal-footer" style="text-align:left;">
    <button id="btnrefer" class="btn btn-default" type="button" style="width:80px; border-radius:px;">ارجاع</button>
    <button class="btn btn-default" type="button" style="width:80px; border-radius:px;" data-dismiss="modal">بازگشت</button>
</div>

<script>
         $(function () {
            $("#jstreejobs").on("changed.jstree", function (e, data) {

                var i, j;
                var postedItems = [];

                j = data.selected.length;
                for (var i = 0; i < j; i++) {
                    postedItems.push({
                        text: data.instance.get_node(data.selected[i]).text,
                        id: data.selected[i],
                        parent: data.node.parents[0]
                    });
                }
                if (data.selected.length) {
                    $("#JobID").val(postedItems[0].id);
                }
                ///////////////////////////////////////
                $("#SelectedUserToRefer").val(JSON.stringify(postedItems));
                ///////////////////////////////////////
            }).jstree({
                "core": {
                    "themes": {
                        "variant":"large"
                    },
                    "data":  @Html.Raw(ViewBag.JobJson) ,
                },
                "checkbox": {
                    "Keep_selected_style":false
                },
                "plugins": ["checkbox"],
                checkbox: {three_state: false, cascade:""}
            }).on("loaded.jstree", function () {
                $.jstree.reference('#jstreejobs').open_all();
                h1('@ViewBag.userJobId');

            });
        });

        function h1(data) {
            //عدد
            parentNode = $('#jstreejobs').jstree(true).get_parent(data);
            //آرایه
            childrenNode = $('#jstreejobs').jstree(true).get_node(data).children;
            //آرایه
            siblingsNode = [];

            //تبدیل پرنت نود به یک آرایه
            prnode = [];
            prnode.push(parentNode);

            //بدست آوردن همترازهای همگروه
            $('#jstreejobs').jstree(true).get_node(parentNode).children.forEach(function (c) {
                if (c !== data) siblingsNode.push(c);
            });

            //نگهدار همه آی دی های مشاغل
            var AllIdjobList = [];
            AllIdjobList = @ViewBag.JobIdList;

            //حذف فرزندان از آرایه همه مشاغل
            for (var i = 0; i < childrenNode.length; i++) {
                removeItem(AllIdjobList, childrenNode[i]);
            }
            //حذف همترازها از آرایه همه مشاغل
            for (var i = 0; i < siblingsNode.length; i++) {
                removeItem(AllIdjobList, siblingsNode[i]);
            }
            //حذف پرنت از آرایه همه مشاغل
            removeItem(AllIdjobList, prnode[0]);

            //غیر فعال کردن همه مشاغل غیر مجاز
              //for (var i = 0; i <= AllIdjobList.length; i++) {
              //    $.jstree.reference('#jstreejobs').disable_node(AllIdjobList[i]);
              //}

            //console.log('child = ' + JSON.stringify(childrenNode));
            //console.log('parent = ' + JSON.stringify(prnode));
            //console.log('siblings = ' + JSON.stringify(siblingsNode));
            //console.log('All = ' + JSON.stringify(AllIdjobList));
        }

        //تابع حذف سلول از آرایه
        function removeItem(arrayTag, itemTag) {
            for (var i in arrayTag) {
                if ($.trim(arrayTag[i]).replace(/ /g, "") == itemTag) {
                    arrayTag.splice(i, 1);
                    break;
                }
            }
    }


       //ارجاع نامه
        $("#btnrefer").on('click', function (e) {
            e.preventDefault();
            //کنترل اینکه کاربر حتما یک شخص را جهت ارسال نامه انتخاب کرده باشد
            if ($("#SelectedUserToRefer").val() == "" || $("#SelectedUserToRefer").val() == '[]') {
                swal({
                        title: "ارجاع نامه",
                        text: "هیچ شخصی جهت ارجاع انتخاب نشده است",
                        type: 'warning',
                        showCancelButton: false,
                        allowOutsideClick: false,
                        confirmButtonColor: "red",
                        confirmButtonText:"باشه"
                    })
                return false;
            }

            $.ajax({
                type: "Post",
                url: '@Url.Action("ReferralLetter","LetterList")',
                data: {
                    'LetterID': $("#LetterId").val(),
                    'SelectedUserToRefer': $("#SelectedUserToRefer").val(),
                    'MainUserId': $("#MainUserId").val(),
                    'Description' : $("#txtdescription").val()
                }
            }).done(function (result) {
                
                if (result.status == 'ok') {
                    swal({
                        title: "ارجاع نامه",
                        text: "نامه شما با موفقیت ارجاع داده شد",
                        type: 'success',
                        showCancelButton: false,
                        allowOutsideClick: false,
                        confirmButtonColor: "green",
                        confirmButtonText:"باشه"
                    }).then(function () {
                        window.location.reload(true);
                    });
                }
                if (result.status == 'nouserselected') {
                       swal({
                        title: "ارجاع نامه",
                        text: "هیچ شخصی جهت ارجاع انتخاب نشده است",
                        type: 'warning',
                        showCancelButton: false,
                        allowOutsideClick: false,
                        confirmButtonColor: "red",
                        confirmButtonText:"باشه"
                    })
                }

                   if (result.status == 'error') {
                       swal({
                        title: "خطا",
                        text: "در ارتباط با سرور مشکلی وجود دارد.",
                        type: 'warning',
                        showCancelButton: false,
                        allowOutsideClick: false,
                        confirmButtonColor: "red",
                        confirmButtonText:"باشه"
                    })
                }

            });
        });
</script>