WebAutomationSystem/Areas/UserArea/Controllers/DefaultFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAutomationSystem.DataModelLayer.Entities;
using WebAutomationSystem.DataModelLayer.Services;
using WebAutomationSystem.DataModelLayer.ViewModels;

namespace WebAutomationSystem.Areas.UserArea.Controllers
{
    [Area("UserArea")]
    [Authorize(Roles = "UserAreaPanel")]
    public class DefaultFormController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUsers> _userManager;

        public DefaultFormController(IUnitOfWork context, 
                                        UserManager<ApplicationUsers> userManager,
                                                 IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View(_context.administrativeFormUW.Get(ad => ad.UserID == _userManager.GetUserId(HttpContext.User) && ad.AdministrativeFormType == false));

        }

        [HttpGet]
        public IActionResult AddNewDefaultForm()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNewDefaultForm(AdministrativeFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.UserID = _userManager.GetUserId(HttpContext.User);
                model.AdministrativeFormType = false;
                _context.administrativeFormUW.Create(_mapper.Map<AdministrativeForm>(model));
                _context.save();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int AdministrativeFormID)
        {
            if (AdministrativeFormID == 0)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            var model = _context.administrativeFormUW.GetById(AdministrativeFormID);
            if (model == null)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            return PartialView("_deleteform", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteForm(int AdministrativeFormID)
        {
            if (AdministrativeFormID == 0)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            try
            {
                _context.administrativeFormUW.DeleteById(AdministrativeFormID);
                _context.save();
                return RedirectToAction("Index");
            }
            catch
            {

                return RedirectToAction("ErrorView", "Home");
            }
        }
    }
}

WebAutomationSystem/Areas/UserArea/Views/DefaultForm/AddNewDefaultForm.cshtml
@model WebAutomationSystem.DataModelLayer.ViewModels.AdministrativeFormViewModel
@{
    ViewData["Title"] = "ثبت نامه پیش فرض جدید";
}


<div class="content">

    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 #cbcbcb; border-radius:px;">
        <span style="font-weight:bold;">
            <i class="icon-package"></i>
            فرم ثبت نامه پیش فرض
        </span>
    </div>


    <div class="panel panel-body container-fluid" style="border-radius:px; box-shadow:3px 1px 1px 0 #cbcbcb;
                background-color:#ebebeb;">

        <form asp-controller="DefaultForm" asp-action="AddNewDefaultForm" method="post">
            <div class="col-md-8 col-md-offset-2">
                <!--AdministrativeFormTitle-->
                <div>
                    <label asp-for="AdministrativeFormTitle" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="AdministrativeFormTitle" type="text" class="form-control custominput" placeholder="عنوان نامه..." autocomplete="off" />
                        <span asp-validation-for="AdministrativeFormTitle" class="text-danger"></span>
                    </div>
                </div>


                <!--AdministrativeFormContent-->
                <div>
                    <label asp-for="AdministrativeFormContent" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <textarea asp-for="AdministrativeFormContent" rows="8" type="text" class="form-control custominput" placeholder="متن نامه..." autocomplete="off"></textarea>
                        <span asp-validation-for="AdministrativeFormContent" class="text-danger"></span>
                    </div>
                </div>



                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <input type="submit" 
                           value="ثبت اطلاعات" class="btn btn-outline-primary pull-right" />
                </div>
            </div>
        </form>
    </div>

</div>

WebAutomationSystem/Areas/UserArea/Views/DefaultForm/Index.cshtml
@model IEnumerable<AdministrativeForm>
@using WebAutomationSystem.CommonLayer.PublicClass

@{
    ViewData["Title"] = "Index";
    int counter = 1;
}

<style>
    tr:hover td {
        background-color: #dcd6d6;
    }
</style>

<div class="content">

    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 #cbcbcb; border-radius:px;">
        <span style="font-weight:bold;">
            <i class="icon-package"></i>
            لیست نامه های پیش فرض شما
        </span>
    </div>

    <div style="margin-bottom:5px;">
        <a class="btn btn-outline-primary" asp-controller="DefaultForm" asp-action="AddNewDefaultForm">
            <i class="glyphicon glyphicon-plus"></i>
            ثبت فرم جدید
        </a>
    </div>
    <div class="panel panel-body container-fluid" style="border-radius:px; box-shadow:3px 1px 1px 0 #cbcbcb; background-color:#ebebeb;">

        <div class="table-responsive" style="border:1px solid #cbcbcb; border-radius:px; box-shadow:3px 3px 1px 0 #cbcbcb;">
            <table class="table table-bordered" style="background-color:white;">
                <thead>
                    <tr style="font-size:14px; font-weight:bold; background-color:#cbcbcb;">
                        <td style="width:60px;">ردیف</td>
                        <td style="width:200px;">موضوع نامه</td>
                        <td>محتوای نامه</td>
                        <td style="width:120px;">عملیات</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr style="font-size:13px;">
                            <td style="width:60px; text-align:center;">@counter</td>
                            <td style="text-align:right;">@item.AdministrativeFormTitle</td>



                            <td style="text-align:right;">
                                @if (item.AdministrativeFormContent.Length > 150)
                                {
                                    @item.AdministrativeFormContent.Substring(0,150) <span style="color:blue;">(ادامه دارد ...)</span>
                                }
                                else
                                {
                                    @item.AdministrativeFormContent
                                }

                            </td>
                            
                            <td>
                                <div class="row">
                                    <a asp-controller="DefaultForm" asp-action="Delete" 
                                       asp-route-AdministrativeFormID="@item.Id"
                                       style="height:30px; width:100px; font-size:10px; margin-bottom:3px;"
                                       data-toggle="modal" data-target="#modal-action"
                                   class="btn btn-outline-danger">
                                        <i class="glyphicon glyphicon-remove"></i>
                                        حذف
                                    </a>
                                </div>

                            </td>
                        </tr>
                        counter++;
                    }

                </tbody>
            </table>
        </div>


    </div>
</div>


@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action", Size = BootstrapModel.ModalSize.Large })

@section UserScripts{
    <script src="~/js/modal/modal.js"></script>
}

WebAutomationSystem/Areas/UserArea/Views/DefaultForm/_deleteform.cshtml
@model WebAutomationSystem.DataModelLayer.Entities.AdministrativeForm

@{
    Layout = null;
}

<form asp-controller="DefaultForm" asp-action="DeleteForm" method="post">
    <div class="modal-header" style="background-color:darkred; color:white; border-radius:5px 5px 0 0;">
        <button type="button" class="close pull-left" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">حذف نامه پیش فرض</h4>
    </div>


        <div class="modal-body form-horizontal">
          آیا از حذف نامه با عنوان <span style="font-weight:bold;">@Model.AdministrativeFormTitle</span> مطمئن هستید؟
        </div>
    

    <input type="hidden" asp-for="Id" />


    <div class="modal-footer" style="text-align:left;">
        <button class="btn btn-default" type="button" style="width:80px;" data-dismiss="modal">بازگشت</button>
        <button type="submit" class="btn" style="width:80px; color:white; background-color:darkred;">
            حذف کن!
        </button>
    </div>

</form>